## 50 câu hỏi ngắn về Numpy

### Câu hỏi 1: import numpy dưới bí danh np và xem phiên bản

In [1]:
import numpy as np
print(np.__version__)

1.26.4


### Câu hỏi 2: Làm thế nào để tạo mảng 1 chiều?

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### Câu hỏi 3: Làm thế nào để tạo một mảng boolean?

In [3]:
import numpy as np
arr = np.array([True, False, True, False])
print(arr)

[ True False  True False]


In [4]:
arr = np.ones(5, dtype=bool)
print(arr)

[ True  True  True  True  True]


In [7]:

arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 2 
print(bool_arr)

[False False  True  True  True]


In [6]:
arr = np.full(5, True, dtype=bool)
print(arr)

[ True  True  True  True  True]


### Câu hỏi 4: Làm thế nào để trích xuất các mục thỏa mãn một điều kiện nhất định từ mảng 1 chiều?
Ví dụ: Trích xuất tất cả các số lẻ từ mảng

In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]


### Câu hỏi 5: Làm thế nào để thay thế các mục thỏa mãn một điều kiện bằng một giá trị khác trong mảng numpy?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 == 1] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


### Câu hỏi 6: Làm thế nào để thay thế các mục thỏa mãn một điều kiện mà không ảnh hưởng đến mảng ban đầu?
Ví dụ: Thay thế tất cả các số lẻ trong arr bằng -1 mà không thay đổi arr

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_arr = arr.copy()
new_arr[new_arr % 2 == 1] = -1
print("Mảng gốc:", arr)
print("Mảng mới:", new_arr)


Mảng gốc: [ 1  2  3  4  5  6  7  8  9 10]
Mảng mới: [-1  2 -1  4 -1  6 -1  8 -1 10]


### Câu hỏi 7: Làm thế nào để định hình lại một mảng?

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


### Câu hỏi 8: Làm thế nào để xếp chồng hai mảng theo chiều dọc?

In [14]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]]


### Câu hỏi 9: Làm thế nào để xếp chồng hai mảng theo chiều ngang?

In [15]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
print(result)

[1 2 3 4 5 6]


### Câu hỏi 10: Làm thế nào để tạo các chuỗi tùy chỉnh trong numpy mà không cần mã hóa cứng?
Ví dụ: 
Input: a = np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
import numpy as np
a = np.array([1, 2, 3])
repeat_part = np.repeat(a, 3)
tile_part = np.tile(a, 3)
result = np.concatenate((repeat_part, tile_part))
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Câu hỏi 11. Làm thế nào để lấy các mục chung giữa hai mảng numpy python?
Ví dụ: 
Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

        b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: array([2, 4])

In [17]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_elements = np.intersect1d(a, b)
print(common_elements)

[2 4]


In [18]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
mask = np.in1d(a, b)
common_elements = np.unique(a[mask])
print(common_elements)

[2 4]


### Câu hỏi 12. Làm thế nào để xóa khỏi một mảng những mục tồn tại trong mảng khác? 
Ví dụ: Input: a = np.array([1,2,3,4,5])

              b = np.array([5,6,7,8,9])

Output: array([1,2,3,4])

In [19]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


### Câu hỏi 13. Làm thế nào để lấy các vị trí mà các phần tử của hai mảng khớp nhau?

Ví dụ: 

Input: a = np.array([1,2,3,2,3,4,3,4,5,6])

       b = np.array([7,2,10,2,7,4,9,4,9,8])

Output: (array([1, 3, 5, 7]),)

In [20]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(a == b)
print(result)

(array([1, 3, 5, 7], dtype=int64),)


### Câu hỏi 14. Làm thế nào để trích xuất tất cả các số trong một phạm vi nhất định từ một mảng numpy?

Ví dụ: 
Input: a = np.array([2, 6, 1, 9, 10, 3, 27])

Output: (array([6, 9, 10]),)

In [21]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
lower_bound = 5
upper_bound = 10
result = a[(a >= lower_bound) & (a <= upper_bound)]
print(result)

[ 6  9 10]


### Câu hỏi 16. Làm thế nào để hoán đổi hai cột trong một mảng numpy 2 chiều? 

In [23]:
import numpy as np
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print("Mảng gốc:")
print(a)
a[:, [0, 2]] = a[:, [2, 0]]
print("\nMảng sau khi hoán đổi cột 0 và cột 2:")
print(a)

Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng sau khi hoán đổi cột 0 và cột 2:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


### Câu hỏi 17. Làm thế nào để hoán đổi hai hàng trong một mảng numpy 2 chiều? 

In [24]:
import numpy as np
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print("Mảng gốc:")
print(a)
a[[0, 2], :] = a[[2, 0], :]
print("\nMảng sau khi hoán đổi hàng 0 và hàng 2:")
print(a)


Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng sau khi hoán đổi hàng 0 và hàng 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Câu hỏi 18. Làm thế nào để đảo ngược các hàng của một mảng 2 chiều? 

In [25]:
import numpy as np
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print("Mảng gốc:")
print(a)
reversed_a = a[::-1, :]
print("\nMảng sau khi đảo ngược các hàng:")
print(reversed_a)


Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng sau khi đảo ngược các hàng:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Câu hỏi 19. Làm thế nào để đảo ngược các cột của một mảng 2 chiều?

In [26]:
import numpy as np
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

print("Mảng gốc:")
print(a)
reversed_columns = a[:, ::-1]
print("\nMảng sau khi đảo ngược các cột:")
print(reversed_columns)

Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mảng sau khi đảo ngược các cột:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


### Câu hỏi 20. Làm thế nào để tạo một mảng 2 chiều chứa các số thực ngẫu nhiên giữa 5 và 10?

In [29]:
import numpy as np
rows, columns = 3, 3
random_array = np.random.uniform(5, 10, size=(rows, columns))
print(random_array)

[[6.24309434 7.30735925 7.0875348 ]
 [5.94996994 6.39149763 9.42349994]
 [7.8464319  9.49864602 8.39866968]]


### Câu hỏi 21. Làm thế nào để chỉ in 3 chữ số thập phân trong mảng numpy python? 

In [30]:
import numpy as np
a = np.random.uniform(5, 10, size=(3, 3))
print("Mảng gốc:")
print(a)
np.set_printoptions(precision=3)
print("\nMảng sau khi thiết lập chỉ in 3 chữ số thập phân:")
print(a)

Mảng gốc:
[[8.44139019 6.42319277 9.67545299]
 [7.34189994 7.20600736 7.80960322]
 [5.53153569 7.40935896 9.92504609]]

Mảng sau khi thiết lập chỉ in 3 chữ số thập phân:
[[8.441 6.423 9.675]
 [7.342 7.206 7.81 ]
 [5.532 7.409 9.925]]


### Câu hỏi 22. Làm thế nào để in đẹp một mảng numpy bằng cách loại bỏ ký hiệu khoa học (như 1e10)? 

In [1]:
import numpy as np
a = np.array([1.23e-4, 2.34e3, 4.56e-2, 7.89e1, 1.23e2])
np.set_printoptions(suppress=True)
print(a)

[   0.000123 2340.          0.0456     78.9       123.      ]


### Câu hỏi 24. Làm thế nào để in toàn bộ mảng numpy mà không cần cắt bớt

In [32]:
import numpy as np
a = np.arange(1000)
print("Mảng gốc với các phần tử bị cắt bớt:")
print(a)
np.set_printoptions(threshold=np.inf)
print("\nMảng sau khi thiết lập để in toàn bộ:")
print(a)

Mảng gốc với các phần tử bị cắt bớt:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 2

### Câu hỏi 28. Làm thế nào để tính giá trị trung bình, trung vị, độ lệch chuẩn của một mảng numpy?

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

gia_tri_trung_binh = np.mean(arr)
trung_vi = np.median(arr)
do_lech_chuan = np.std(arr)

print(f"Giá trị trung bình: {gia_tri_trung_binh}")
print(f"Trung vị: {trung_vi}")
print(f"Độ lệch chuẩn: {do_lech_chuan}")


Giá trị trung bình: 5.0
Trung vị: 5.0
Độ lệch chuẩn: 2.581988897471611


### Câu hỏi 29. Làm thế nào để chuẩn hóa một mảng sao cho các giá trị nằm chính xác trong khoảng từ 0 đến 1?

In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

arr_min = np.min(arr)
arr_max = np.max(arr)

arr_normalized = (arr - arr_min) / (arr_max - arr_min)

print("Mảng sau khi chuẩn hóa:", arr_normalized)


Mảng sau khi chuẩn hóa: [0.   0.25 0.5  0.75 1.  ]


### Câu hỏi 30. Làm thế nào để tính điểm softmax?

In [6]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x))  
    return exp_x / np.sum(exp_x)

arr = np.array([2.0, 1.0, 0.1])
softmax_values = softmax(arr)

print("Giá trị softmax:", softmax_values)

Giá trị softmax: [0.65900114 0.24243297 0.09856589]


### Câu hỏi 32. Làm thế nào để chèn các giá trị ở các vị trí ngẫu nhiên trong một mảng?

Ví dụ: Chèn giá trị 0 vào 20 vị trí ngẫu nhiên trong tập dữ liệu a

In [7]:
import numpy as np
a = np.arange(1, 101)  
num_insertions = 20
random_indices = np.random.choice(len(a), num_insertions, replace=False)
a[random_indices] = 0
print("Mảng sau khi chèn 0 vào các vị trí ngẫu nhiên:")
print(a)

Mảng sau khi chèn 0 vào các vị trí ngẫu nhiên:
[  1   2   3   4   5   6   7   8   0  10  11  12   0   0  15  16  17  18
  19   0   0  22   0  24  25  26  27  28  29   0  31  32  33  34  35  36
  37   0  39   0  41   0  43   0  45  46  47  48  49  50  51  52  53  54
  55  56   0  58  59  60   0  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76   0  78  79  80   0  82   0   0  85  86   0  88  89   0
  91  92  93  94  95  96  97  98   0 100]


### Câu hỏi 34. Làm thế nào để lọc một mảng numpy dựa trên hai hoặc nhiều điều kiện?

Ví dụ: Lọc các hàng của a có các giá trị của (cột thứ 3) > 1,5 và các giá trị (cột thứ 1) < 5,0

In [8]:
import numpy as np
np.random.seed(42)  
a = np.random.rand(5, 3) * 10  
filtered_rows = a[(a[:, 2] > 1.5) & (a[:, 0] < 5.0)]

print("Mảng ban đầu:")
print(a)
print("\nMảng sau khi lọc:")
print(filtered_rows)

Mảng ban đầu:
[[3.74540119 9.50714306 7.31993942]
 [5.98658484 1.5601864  1.5599452 ]
 [0.58083612 8.66176146 6.01115012]
 [7.08072578 0.20584494 9.69909852]
 [8.32442641 2.12339111 1.81824967]]

Mảng sau khi lọc:
[[3.74540119 9.50714306 7.31993942]
 [0.58083612 8.66176146 6.01115012]]


### Câu hỏi 36. Làm thế nào để tìm mối tương quan giữa hai cột của mảng numpy?

In [9]:
import numpy as np
np.random.seed(42) 
a = np.random.rand(5, 3) * 10  
correlation_matrix = np.corrcoef(a[:, 0], a[:, 2])

correlation_value = correlation_matrix[0, 1]

print("Mảng dữ liệu:")
print(a)
print("\nHệ số tương quan giữa cột 1 và cột 3:", correlation_value)

Mảng dữ liệu:
[[3.74540119 9.50714306 7.31993942]
 [5.98658484 1.5601864  1.5599452 ]
 [0.58083612 8.66176146 6.01115012]
 [7.08072578 0.20584494 9.69909852]
 [8.32442641 2.12339111 1.81824967]]

Hệ số tương quan giữa cột 1 và cột 3: -0.2723364830947168


### Câu hỏi 44. Làm thế nào để sắp xếp một mảng 2D theo một cột

In [10]:
import numpy as np
np.random.seed(42)
a = np.random.randint(1, 100, (5, 3))  
sorted_array = a[a[:, 1].argsort()]

print("Mảng ban đầu:")
print(a)
print("\nMảng sau khi sắp xếp theo cột thứ 2:")
print(sorted_array)

Mảng ban đầu:
[[52 93 15]
 [72 61 21]
 [83 87 75]
 [75 88 24]
 [ 3 22 53]]

Mảng sau khi sắp xếp theo cột thứ 2:
[[ 3 22 53]
 [72 61 21]
 [83 87 75]
 [75 88 24]
 [52 93 15]]


### Câu hỏi 45. Làm thế nào để tìm giá trị thường xuyên nhất trong một mảng numpy?

In [11]:
import numpy as np
from scipy.stats import mode
a = np.array([1.1, 2.2, 3.3, 2.2, 2.2, 3.3, 3.3, 3.3, 1.1])
most_frequent = mode(a, keepdims=False)

print("Giá trị xuất hiện nhiều nhất:", most_frequent.mode)
print("Số lần xuất hiện:", most_frequent.count)


Giá trị xuất hiện nhiều nhất: 3.3
Số lần xuất hiện: 4


### Câu hỏi 47. Làm thế nào để thay thế tất cả các giá trị lớn hơn một giá trị nhất định thành một ngưỡng nhất định?

Ví dụ: Từ mảng a, thay thế tất cả các giá trị lớn hơn 30 đến 30 và nhỏ hơn 10 đến 10.

In [12]:
import numpy as np
np.random.seed(42)
a = np.random.randint(1, 50, 10) 
a_clipped = np.clip(a, 10, 30)

print("Mảng ban đầu:")
print(a)
print("\nMảng sau khi thay thế:")
print(a_clipped)

Mảng ban đầu:
[39 29 15 43  8 21 39 19 23 11]

Mảng sau khi thay thế:
[30 29 15 30 10 21 30 19 23 11]


### Câu hỏi 48. Làm thế nào để lấy vị trí của n giá trị hàng đầu từ một mảng numpy?

Ví dụ: Lấy vị trí của 5 giá trị lớn nhất trong một mảng cho trước a.

In [13]:
import numpy as np
np.random.seed(42)
a = np.random.randint(1, 100, 10) 
n = 5
top_n_indices = np.argsort(a)[-n:][::-1]  
print("Mảng ban đầu:")
print(a)
print("\nVị trí của 5 giá trị lớn nhất:")
print(top_n_indices)
print("Giá trị tương ứng:")
print(a[top_n_indices])

Mảng ban đầu:
[52 93 15 72 61 21 83 87 75 75]

Vị trí của 5 giá trị lớn nhất:
[1 7 6 9 8]
Giá trị tương ứng:
[93 87 83 75 75]


### Câu hỏi 50. Làm thế nào để chuyển đổi một mảng các mảng thành một mảng phẳng 1 chiều?

In [14]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])

flattened = a.ravel()
print("Mảng ban đầu:")
print(a)
print("\nMảng phẳng:")
print(flattened)

Mảng ban đầu:
[[1 2 3]
 [4 5 6]]

Mảng phẳng:
[1 2 3 4 5 6]


In [15]:
flattened = a.flatten()
print("\nMảng phẳng (dùng flatten()):")
print(flattened)



Mảng phẳng (dùng flatten()):
[1 2 3 4 5 6]
